services:
  postgres:
    image: postgres:16
    container_name: golfiq_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: golfiq_user
      POSTGRES_PASSWORD: golfiq_password
      POSTGRES_DB: golfiq_dev

    ports:
      - "5433:5432"

    volumes:
      - golfiq_postgres_data:/var/lib/postgresql/data

volumes:
  golfiq_postgres_data: